### Add batch
http://localhost:8080/api/batch/run?name=aaa

### List batch
http://localhost:8080/api/batch/

### Read batch content
http://localhost:8080/api/batch/read?name=aaa

### Explode batch content
http://localhost:8080/api/batch/explode?name=aaa

### Download offers from batch
http://localhost:8080/api/batch/offers/download?name=aaa&number=100

### Link technologies from offers from batch
http://localhost:8080/api/batch/offers/link?name=aaa

### Get presentation
http://localhost:8080/api/batch/presentation?name=aaa
